function __mergeLine(line){const compact=line.filter((n)=>n!==0),merged=[];let gained=0;for(let i=0;i<compact.length;i++){if(i+1<compact.length&&compact[i]===compact[i+1]){const v=compact[i]*2;merged.push(v);gained+=v;i++}else merged.push(compact[i])}while(merged.length<line.length)merged.push(0);return{line:merged,gained}}
function __mergeApplyMove(board,direction,width=4){const next=board.slice();let gained=0;for(let n=0;n<width;n++){const indices=[];for(let i=0;i<width;i++)indices.push(direction==='left'||direction==='right'?n*width+i:i*width+n);let values=indices.map((i)=>board[i]);const reverse=direction==='right'||direction==='down';if(reverse)values=values.reverse();const r=__mergeLine(values);gained+=r.gained;const out=reverse?r.line.slice().reverse():r.line;indices.forEach((idx,i)=>{next[idx]=out[i]})}return{board:next,gained,changed:next.some((v,i)=>v!==board[i])}}
function __mergeCanMove(board,width=4){if(board.some((v)=>v===0))return true;for(let r=0;r<width;r++)for(let c=0;c<width;c++){const i=r*width+c;if(c+1<width&&board[i]===board[i+1])return true;if(r+1<width&&board[i]===board[i+width])return true}return false}
document.addEventListener('DOMContentLoaded',()=>{
  const grid=document.querySelector('.grid'),scoreEl=document.getElementById('score'),scoreBox=document.querySelector('.score-container'),result=document.getElementById('result'),width=4,cells=[];let board=Array(width*width).fill(0),score=0,ended=false;
  function render(spawned=-1,gained=0){board.forEach((v,i)=>{const cell=cells[i];cell.textContent=v?String(v):'';cell.dataset.value=String(v);cell.classList.toggle('spawn',i===spawned)});scoreEl.textContent=String(score);if(gained>0){scoreBox.classList.remove('pop');void scoreBox.offsetWidth;scoreBox.classList.add('pop')}window.parent.postMessage({__hub:1,type:'score',value:score},'*')}
  function spawn(){const empty=[];board.forEach((v,i)=>{if(v===0)empty.push(i)});if(!empty.length)return-1;const idx=empty[Math.floor(Math.random()*empty.length)];board[idx]=Math.random()<.9?2:4;return idx}
  function finish(text){if(ended)return;ended=true;result.textContent=text;document.removeEventListener('keyup',control)}
  function move(direction){if(ended)return;const r=__mergeApplyMove(board,direction,width);if(!r.changed){grid.classList.remove('bump');void grid.offsetWidth;grid.classList.add('bump');if(!__mergeCanMove(board,width))finish('Игра окончена');return}board=r.board;score+=r.gained;const spawned=spawn();render(spawned,r.gained);if(board.some((v)=>v>=2048))finish('Победа ✦');else if(!__mergeCanMove(board,width))finish('Игра окончена')}
  function control(e){if(e.key==='ArrowLeft'||e.keyCode===37)move('left');else if(e.key==='ArrowUp'||e.keyCode===38)move('up');else if(e.key==='ArrowRight'||e.keyCode===39)move('right');else if(e.key==='ArrowDown'||e.keyCode===40)move('down')}
  for(let i=0;i<width*width;i++){const cell=document.createElement('div');cell.dataset.value='0';grid.appendChild(cell);cells.push(cell)}result.textContent='';const a=spawn(),b=spawn();render(b);cells[a]?.classList.add('spawn');document.addEventListener('keyup',control);
  let sx=0,sy=0;grid.addEventListener('touchstart',(e)=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});grid.addEventListener('touchend',(e)=>{const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)<20&&Math.abs(dy)<20)return;move(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'))},{passive:true});
});
