#!/usr/bin/env node
import { readFileSync } from 'node:fs';import vm from 'node:vm';import { join,dirname } from 'node:path';import { fileURLToPath } from 'node:url';
const ROOT=join(dirname(fileURLToPath(import.meta.url)),'..'),SAPPER=join(ROOT,'games','sapper','script.js'),QUIZ=join(ROOT,'games','quiz','script.js'),SEED_A='2026-09-06',SEED_B='2026-01-01';
function mkEl(){return{innerHTML:'',textContent:'',value:'',type:'',name:'',checked:false,disabled:false,children:[],style:{},dataset:{},classList:{contains:()=>false,add(){},remove(){},toggle(){}},addEventListener(){},removeEventListener(){},appendChild(x){this.children.push(x)},append(x){this.children.push(x)},removeChild(){},setAttribute(){},getAttribute:()=>null,querySelector:()=>mkEl(),querySelectorAll:()=>[]}}
function runGame(file,seed,exportExpr,pre=''){const code=readFileSync(file,'utf8').replace(/\r\n/g,'\n');const wrapped=code+`\n;globalThis.__run=function(){${pre}};globalThis.__export=()=>(${exportExpr});`;const sandbox={Math,Date,console,URLSearchParams,JSON,setTimeout(){},location:{search:seed?`?seed=${seed}`:''},window:{parent:{postMessage(){}},addEventListener(){},onload:null},document:{getElementById:()=>mkEl(),createElement:()=>mkEl(),createTextNode:()=>mkEl(),querySelector:()=>mkEl(),querySelectorAll:()=>[],addEventListener(){}}};sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(wrapped,sandbox,{filename:file});sandbox.__run();return sandbox.__export()}
let fails=0;function ok(cond,msg){console.log(`${cond?'✓':'✗'} ${msg}`);if(!cond)fails++}
const sa1=runGame(SAPPER,SEED_A,'minesLocation','setMines();'),sa2=runGame(SAPPER,SEED_A,'minesLocation','setMines();'),sa3=runGame(SAPPER,SEED_B,'minesLocation','setMines();');ok(sa1.length===10&&new Set(sa1).size===10,'сапёр: 10 уникальных мин');ok(JSON.stringify(sa1)===JSON.stringify(sa2),'сапёр: одинаковый seed => одинаковая раскладка');ok(JSON.stringify(sa1)!==JSON.stringify(sa3),'сапёр: разный seed => разная раскладка');
const q1=runGame(QUIZ,SEED_A,'quizData.map(q=>q.question)'),q2=runGame(QUIZ,SEED_A,'quizData.map(q=>q.question)'),q3=runGame(QUIZ,SEED_B,'quizData.map(q=>q.question)');ok(q1.length===10,'викторина: короткий daily из 10 вопросов');ok(JSON.stringify(q1)===JSON.stringify(q2),'викторина: одинаковый seed => одинаковый набор и порядок');ok(JSON.stringify(q1)!==JSON.stringify(q3),'викторина: разный seed => другой набор/порядок');const quizSource=readFileSync(QUIZ,'utf8');ok(quizSource.includes('shuffleArray(questionBank)')&&!quizSource.includes('.sort(() => __hubRand'),'вопросы перемешиваются Fisher–Yates, а не engine-dependent Array.sort');
console.log(fails===0?'\nПазл дня детерминирован. Всё ок.':`\nПровалено проверок: ${fails}`);process.exit(fails===0?0:1);
